# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e44b2617-5959-4a44-9585-c5a4a6d354e9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e44b2617-5959-4a44-9585-c5a4a6d354e9".device = "/dev/disk/by-uuid/e44b2617-5959-4a44-9585-c5a4a6d354e9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/94A4-99D0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ec760052-6601-442e-b3cc-6a95fd0a55f1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
